wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/cleanrl/double_dqn.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.20
    start_time: 1733895047.120801
    t:
      1:
      - 1
      - 2
      - 3
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.20
      5: 0.13.11
      8:
      - 5
batch_size:
  desc: null
  value: 128
buffer_size:
  desc: null
  value: 10000
capture_video:
  desc: null
  value: true
cuda:
  desc: null
  value: false
end_e:
  desc: null
  value: 0.05
env_id:
  desc: null
  value: CartPole-v0
exp_name:
  desc: null
  value: double_dqn
exploration_fraction:
  desc: null
  value: 0.5
gamma:
  desc: null
  value: 0.99
hf_entity:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 0.00025
learning_starts:
  desc: null
  value: 10000
num_envs:
  desc: null
  value: 1
save_model:
  desc: null
  value: false
seed:
  desc: null
  value: 22520750
start_e:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 500
tau:
  desc: null
  value: 1.0
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 100000
track:
  desc: null
  value: true
train_frequency:
  desc: null
  value: 10
upload_model:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cartpole
